// Mocks generated by Mockito 5.3.2 from annotations
// in field_drawer/domain/welcome_screen_vm.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:field_drawer/back/permissions.dart' as _i2;
import 'package:field_drawer/domain/welcome_screen_vm.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePermissionsService_0 extends _i1.SmartFake
    implements _i2.PermissionsService {
  _FakePermissionsService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnackbarService_1 extends _i1.SmartFake
    implements _i3.SnackbarService {
  _FakeSnackbarService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WelcomeScreenVm].
///
/// See the documentation for Mockito's code generation for more information.
class MockWelcomeScreenVm extends _i1.Mock implements _i4.WelcomeScreenVm {
  @override
  _i2.PermissionsService get permissionsService => (super.noSuchMethod(
        Invocation.getter(#permissionsService),
        returnValue: _FakePermissionsService_0(
          this,
          Invocation.getter(#permissionsService),
        ),
        returnValueForMissingStub: _FakePermissionsService_0(
          this,
          Invocation.getter(#permissionsService),
        ),
      ) as _i2.PermissionsService);
  @override
  _i3.SnackbarService get snackbarService => (super.noSuchMethod(
        Invocation.getter(#snackbarService),
        returnValue: _FakeSnackbarService_1(
          this,
          Invocation.getter(#snackbarService),
        ),
        returnValueForMissingStub: _FakeSnackbarService_1(
          this,
          Invocation.getter(#snackbarService),
        ),
      ) as _i3.SnackbarService);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i5.Future<void> internetConnectionSnackbar() => (super.noSuchMethod(
        Invocation.method(
          #internetConnectionSnackbar,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> checkLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkLocationPermission,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
