name: field_drawer
description: Satagro task.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.0.0
  stacked_services: ^0.9.5
  logger: ^1.1.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  mockito: ^5.3.2
  flutter_animated_dialog: ^2.0.1
  dropdown_search: ^5.0.3
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  geocoder2: ^1.4.0
  searchable_listview: ^2.1.1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  dartz: ^0.10.1

  google_maps_flutter: ^2.2.1
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  permission_handler: ^9.2.0
  flutter_native_splash: ^2.2.11
  path_provider: ^2.0.11
  provider: ^6.0.4
  firebase_auth: ^3.11.2
  google_sign_in: ^5.4.2
  firebase_core: ^1.24.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  json_annotation: ^4.7.0
#generators
  json_serializable: ^6.5.0
  build_runner: ^2.2.1
  stacked_generator: ^0.8.0+1
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0


flutter:


  uses-material-design: true

  assets:
    - assets/entries/
    - assets/pictures/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
